# Generated by Django 4.2.29 on 2026-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
